name: Run Checks (Unit Tests, Linting, etc.)

on:
  push:
    branches:
      - main
      - version/v*
  pull_request:
    branches:
      - main
      - version/v*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js with Corepack
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test

      - name: Run linting
        run: yarn lint

      - name: Run formatting checks
        run: yarn format
